"""
Report domain model - represents generated analysis reports.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class ReportType(str, Enum):
    """Type of report generated."""
    ROUND_SUMMARY = "round_summary"
    LINEAGE_ANALYSIS = "lineage_analysis"
    CAMPAIGN_SUMMARY = "campaign_summary"
    VARIANT_COMPARISON = "variant_comparison"
    CAMPAIGN_PROGRESS = "campaign_progress"
    FINAL_REPORT = "final_report"


class Report(BaseModel):
    """
    Report entity - represents an analysis report generated by the reporter agent.

    Domain Invariants:
    1. Every report must belong to a round
    2. Report type and format must be specified
    3. Content can be stored inline or in S3
    """

    id: UUID = Field(default_factory=uuid4)
    campaign_id: Optional[UUID] = None
    round_id: UUID
    report_type: str = Field(..., description="Type: 'round_summary', 'lineage_analysis', etc.")
    format: str = Field(..., description="Format: 'markdown', 'json', 'html'")
    content: Optional[Any] = Field(None, description="Small reports stored inline")
    storage_path: Optional[str] = Field(None, description="S3 path for large reports")
    meta_data: dict = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
