"""Round domain model - represents a single evolution iteration."""

from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class RoundStatus(str, Enum):
    """Round execution states."""

    PENDING = "pending"
    PLANNING = "planning"
    GENERATING = "generating"
    EVALUATING = "evaluating"
    SELECTING = "selecting"
    REPORTING = "reporting"
    COMPLETED = "completed"
    FAILED = "failed"


class Round(BaseModel):
    """
    Round entity - represents one iteration of the evolution loop.

    Domain Invariant: Every round belongs to exactly one campaign.

    Execution Flow:
    pending → planning → generating → evaluating → selecting → reporting → completed
    """

    id: UUID = Field(default_factory=uuid4)
    campaign_id: UUID = Field(description="Parent campaign (non-negotiable FK)")
    round_number: int = Field(ge=1, description="Round sequence number (1-indexed)")
    status: RoundStatus = Field(default=RoundStatus.PENDING)
    plan: Optional[dict] = Field(
        None,
        description="Plan generated by PlannerAgent (population, mutation config, etc.)"
    )
    metrics: dict = Field(
        default_factory=dict,
        description="Round performance metrics (duration, scores, etc.)"
    )
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    deleted_at: Optional[datetime] = None

    def start_planning(self) -> None:
        """Transition to planning phase."""
        if self.status != RoundStatus.PENDING:
            raise ValueError(f"Cannot start planning from status {self.status}")
        self.status = RoundStatus.PLANNING
        self.started_at = datetime.utcnow()
        self.updated_at = datetime.utcnow()

    def start_generating(self, plan: dict) -> None:
        """Transition to variant generation phase."""
        if self.status != RoundStatus.PLANNING:
            raise ValueError(f"Cannot start generating from status {self.status}")
        self.plan = plan
        self.status = RoundStatus.GENERATING
        self.updated_at = datetime.utcnow()

    def start_evaluating(self) -> None:
        """Transition to evaluation phase."""
        if self.status != RoundStatus.GENERATING:
            raise ValueError(f"Cannot start evaluating from status {self.status}")
        self.status = RoundStatus.EVALUATING
        self.updated_at = datetime.utcnow()

    def start_selecting(self) -> None:
        """Transition to selection phase."""
        if self.status != RoundStatus.EVALUATING:
            raise ValueError(f"Cannot start selecting from status {self.status}")
        self.status = RoundStatus.SELECTING
        self.updated_at = datetime.utcnow()

    def start_reporting(self) -> None:
        """Transition to reporting phase."""
        if self.status != RoundStatus.SELECTING:
            raise ValueError(f"Cannot start reporting from status {self.status}")
        self.status = RoundStatus.REPORTING
        self.updated_at = datetime.utcnow()

    def complete(self, metrics: Optional[dict] = None) -> None:
        """Mark round as completed."""
        if self.status != RoundStatus.REPORTING:
            raise ValueError(f"Cannot complete from status {self.status}")
        self.status = RoundStatus.COMPLETED
        if metrics:
            self.metrics.update(metrics)
        self.completed_at = datetime.utcnow()
        self.updated_at = datetime.utcnow()

    def fail(self, error_info: Optional[dict] = None) -> None:
        """Mark round as failed."""
        self.status = RoundStatus.FAILED
        if error_info:
            self.metrics["error"] = error_info
        self.updated_at = datetime.utcnow()

    def soft_delete(self) -> None:
        """Soft delete this round (for audit trail)."""
        self.deleted_at = datetime.utcnow()

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "id": "660e8400-e29b-41d4-a716-446655440001",
                    "campaign_id": "550e8400-e29b-41d4-a716-446655440000",
                    "round_number": 1,
                    "status": "completed",
                    "plan": {
                        "population_size": 10,
                        "mutation_rate": 0.3,
                        "parent_ids": [],
                    },
                    "metrics": {
                        "duration_seconds": 120,
                        "variants_generated": 10,
                        "avg_score": 0.75,
                    },
                }
            ]
        }
    }
